name: SALT GYPSY
favicon: null
layout_spectrum: 0.3631780166178942
typography_spectrum: 0.12094901665113866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6690691998228431
  lightness: 0.31818456621840596
  saturation: 0.9022107543423772
  rhythmicContrast: 0.8692989556584507
purpose: []
